name: PHP 8.3.7 CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up PHP 8.3.7
    - name: Set up PHP 8.3.7
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3.7'

    # Install dependencies
    - name: Install Composer
      run: curl -sS https://getcomposer.org/installer | php

    - name: Install dependencies
      run: |
        php composer.phar install --no-interaction --prefer-dist --optimize-autoloader

    # Give execute permission to phpunit
    - name: Give execute permission to PHPUnit
      run: chmod +x ./vendor/bin/phpunit

    # Run PHPUnit tests
    - name: Run tests with PHPUnit
      run: |
        ./vendor/bin/phpunit --configuration phpunit.xml
